model_params:
  model: Unet
  encoder_name: "resnet34"
  activation: 'sigmoid'
  classes: 1

args:
  expdir: "src"
  logdir: &logdir "./logs/siim"
  baselogdir: "./logs/siim"

distributed_params:
  opt_level: O1

stages:

  state_params:
    main_metric: &reduce_metric dice
    minimize_metric: False

  criterion_params:
    criterion: BCEWithLogitsLoss

  data_params:
    batch_size: 64
    num_workers: 8
    drop_last: False
    # drop_last: True

    image_size: &image_size 256
    train_csv: "./csv/train_0.csv"
    valid_csv: "./csv/valid_0.csv"
    root: "/raid/data/kaggle/siim/siim256/"

  stage0:

    optimizer_params:
      optimizer: Adam
      lr: 0.001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [10, 20, 30]
      gamma: 0.2

    state_params:
      num_epochs: 3

    callbacks_params: &callback_params
      loss:
        callback: CriterionCallback
      optimizer:
        callback: OptimizerCallback
        accumulation_steps: 2
      dice:
        callback: DiceCallbackApex
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback


  stage1:

    optimizer_params:
      optimizer: Adam
      lr: 0.0001

    scheduler_params:
      scheduler: OneCycleLR
      num_steps: &num_epochs 20
      lr_range: [0.0005, 0.00001]
      warmup_steps: 3
      momentum_range: [0.85, 0.95]

    state_params:
      num_epochs: *num_epochs

    callbacks_params: *callback_params