model_params:
  model: Unet
  encoder_name: "resnet34"
  activation: 'sigmoid'
  classes: 1

args:
  expdir: "src"
  logdir: &logdir "./logs/siim"
  baselogdir: "./logs/siim"

distributed_params:
  opt_level: O1

stages:

  state_params:
    main_metric: &reduce_metric dice
    minimize_metric: False

  criterion_params:
    criterion: BCEFocalLossApex

  data_params:
    batch_size: 64
    num_workers: 8
    drop_last: False
    # drop_last: True

    image_size: &image_size 1024
    train_csv: "./csv/train_0.csv"
    valid_csv: "./csv/valid_0.csv"
    root: "/raid/data/kaggle/siim/siim256/"

  stage1:

    optimizer_params:
      optimizer: SGD
      lr: 0.01

    scheduler_params:
      scheduler: CyclicLRFix
      step_size_up: 67
      base_lr: 0.001
      max_lr: 0.01
      cycle_momentum: True
      mode: "exp_range"

    state_params:
      num_epochs: 10

    callbacks_params:
      loss:
        callback: CriterionCallback
      optimizer:
        callback: OptimizerCallback
        accumulation_steps: 2
      dice:
        callback: DiceCallbackApex
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
        mode: 'batch'
      saver:
        callback: CheckpointCallback
